Metrics/BlockLength:
  Exclude:
    - 'spec/*.*/*.rb'
AllCops:
  Exclude:
    - '**/*.gemspec'
    - 'exe/*'
    - '**/Gemfile'
    - '.github/**/*'
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec
