#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

begin
  require 'pivotal-tracker'
rescue
  puts "Error: Pivotal Tracker ruby gem must be installed"
  exit
end

def main

  if ENV['PIVOTAL_API_KEY'].nil? or ENV['PIVOTAL_PROJECT_ID'].nil?
    puts "\nYou must have both PIVOTAL_PROJECT_ID and PIVOTAL_API_KEY\nset and valid in your shell environment, or things will go bad\n\n"
    exit
  end

  api_key = ENV['PIVOTAL_API_KEY']
  PivotalTracker::Client.token = api_key
  project = PivotalTracker::Project.find(ENV['PIVOTAL_PROJECT_ID'].to_i)
  stories = project.stories.all({current_state: :started})
  stories.each_with_index{|s,i| puts "[#{i+1}] ##{s.id} : #{s.name}"}

  story_selection = nil
  branch_name = nil

  puts "Select a story"

  while story_selection == nil or story_selection == 0 or story_selection > stories.length + 1
    puts "invalid selection" if story_selection != nil
    story_selection = gets.chomp.to_i
  end

  story = stories[story_selection - 1]

  puts "##{story.id} : #{story.name} - Selected!"

  current_branch = `git rev-parse --abbrev-ref HEAD`.chomp

  puts "Current branch: #{current_branch}"

  if current_branch == "master"
    puts "Create feature branch:"
    branch_name = gets.chomp

    # TODO: Validate that branchname is 'legal'
    # TODO: Validate that branchname doesn't exist
    fq_branch_name = "#{branch_name}-#{story.id}"
    puts "Creating: #{fq_branch_name}"
    `git checkout -b #{fq_branch_name}`

  end
end

main
